// Tests for shader export

import { exportAnimatedHTML, exportGLSL } from '../lib/export';
import type { NodeInstance, Edge, AnimationData } from '../lib/types';

// Mock node data for testing
const mockNodes: NodeInstance[] = [
  {
    id: 'uv1',
    type: 'input_uv',
    position: { x: 0, y: 0 },
    params: {}
  },
  {
    id: 'output1',
    type: 'output',
    position: { x: 200, y: 0 },
    params: {}
  }
];

const mockEdges: Edge[] = [
  {
    id: 'e1',
    source: 'uv1',
    sourceHandle: 'uv',
    target: 'output1',
    targetHandle: 'color'
  }
];

const mockAnimation: AnimationData = {
  tracks: [
    {
      nodeId: 'test',
      paramName: 'value',
      keyframes: [
        { time: 0, value: 0, interpolation: 'linear' },
        { time: 1, value: 1, interpolation: 'easeInOut' }
      ]
    }
  ],
  duration: 2,
  loop: true
};

describe('exportAnimatedHTML', () => {
  it('generates valid HTML document', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, null);
    
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<canvas');
    expect(html).toContain('</html>');
  });

  it('includes WebGL shader setup', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, null);
    
    expect(html).toContain('getContext(\'webgl\')');
    expect(html).toContain('createShader');
    expect(html).toContain('createProgram');
  });

  it('includes uniforms', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, null);
    
    expect(html).toContain('u_resolution');
    expect(html).toContain('u_time');
    expect(html).toContain('u_mouse');
  });

  it('includes playback controls', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, null);
    
    expect(html).toContain('playBtn');
    expect(html).toContain('resetBtn');
    expect(html).toContain('timeDisplay');
  });

  it('uses custom options', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, null, {
      width: 800,
      height: 600,
      title: 'My Shader'
    });
    
    expect(html).toContain('width="800"');
    expect(html).toContain('height="600"');
    expect(html).toContain('<title>My Shader</title>');
  });

  it('includes animation code when animation provided', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, mockAnimation);
    
    expect(html).toContain('animationTracks');
    expect(html).toContain('interpolateTrack');
    expect(html).toContain('easeIn');
    expect(html).toContain('easeOut');
    expect(html).toContain('easeInOut');
    expect(html).toContain('lerpValue');
  });

  it('includes animation duration', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, mockAnimation, {
      duration: 5
    });
    
    expect(html).toContain('const duration = 5');
  });

  it('includes loop option', () => {
    const htmlLoop = exportAnimatedHTML(mockNodes, mockEdges, null, { loop: true });
    const htmlNoLoop = exportAnimatedHTML(mockNodes, mockEdges, null, { loop: false });
    
    expect(htmlLoop).toContain('const loop = true');
    expect(htmlNoLoop).toContain('const loop = false');
  });

  it('includes mouse tracking', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, null);
    
    expect(html).toContain('onmousemove');
    expect(html).toContain('mouseX');
    expect(html).toContain('mouseY');
  });

  it('includes render loop', () => {
    const html = exportAnimatedHTML(mockNodes, mockEdges, null);
    
    expect(html).toContain('requestAnimationFrame');
    expect(html).toContain('function render()');
  });
});

describe('exportGLSL', () => {
  it('generates GLSL code', () => {
    const glsl = exportGLSL(mockNodes, mockEdges);
    
    expect(glsl).toContain('precision highp float');
    expect(glsl).toContain('uniform vec2 u_resolution');
    expect(glsl).toContain('uniform float u_time');
  });

  it('includes comment header', () => {
    const glsl = exportGLSL(mockNodes, mockEdges);
    
    expect(glsl).toContain('// Generated by Prism');
  });
});
